#Locators for Login Module 
Browser = chrome
Url = https://analogfotografy.org/
objsignin_button = //a[contains(.,'Sign in')]
objsign_in = //a[normalize-space()='Sign In']
objuser = //input[@placeholder='Email or Username']
objpass = (//input[contains(@placeholder,'Password')])[1]
objsignin =//form[@data-url='core/signin.php']//div[@class='form-group d-grid']
objusername_error=//div[@id='signin-user-error']
objpassword_error=//div[@id='signin-password-error']
objprofile_button =//a[contains(@aria-expanded,'false')]
objsignout = (//a[contains(normalize-space(),'Sign Out')])[1]