Browser = Chrome
Url = https://analogfotografy.org/

objsignin_button = //a[contains(.,'Sign in')]
objsign_in = //a[normalize-space()='Sign In']

objuser = //input[@placeholder='Email or Username']
objpass = //input[contains(@placeholder,'Password')]

objsignin = //form[@data-url='core/signin.php']//button[@type='submit']


objusername_error = //div[@id='signin-user-error']
objpassword_error = //div[@id='signin-password-error']

objprofile_button = //a[contains(@title,'Account')]
objsignout = //a[normalize-space()='Sign Out']